use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn read(path: &Path) -> String {
    println!("cargo:rerun-if-changed={}", path.display());
    fs::read_to_string(path)
        .unwrap()
        .replace("\r\n", "\n")
        .trim()
        .to_owned()
}

fn emit(out: &Path, assets: &mut String, path: &str, body: &str) {
    let file = format!("asset-{}.txt", assets.lines().count());
    fs::write(out.join(&file), body).unwrap();
    assets.push_str(&format!("Asset {{ path: {path:?}, body: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file}\")) }},\n"));
}

fn main() {
    let root = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap()).join("../..");
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let mut assets = String::new();
    for (agent, skill_root) in [
        ("claude", ".claude/skills"),
        ("github", ".github/skills"),
        ("codex", ".agents/skills"),
    ] {
        for skill in ["arp4", "arp4-setup"] {
            let dir = root.join("surface/skills").join(skill);
            println!("cargo:rerun-if-changed={}", dir.display());
            let read = |name: &str| read(&dir.join(name));
            let fragment = |text: String| {
                text.lines()
                    .filter(|line| !line.trim().is_empty() && !line.trim_start().starts_with('#'))
                    .collect::<Vec<_>>()
                    .join("\n")
            };
            let common = fragment(read("frontmatter.common.yaml"));
            let platform = fragment(read(&format!("frontmatter.{agent}.yaml")));
            let body = read("body.md");
            let front = [common, platform]
                .into_iter()
                .filter(|v| !v.is_empty())
                .collect::<Vec<_>>()
                .join("\n");
            emit(
                &out,
                &mut assets,
                &format!("{skill_root}/{skill}/SKILL.md"),
                &format!("---\n{front}\n---\n\n{body}\n"),
            );
            let references = dir.join("references");
            if references.is_dir() {
                let mut paths: Vec<_> = fs::read_dir(references)
                    .unwrap()
                    .map(|e| e.unwrap().path())
                    .collect();
                paths.sort();
                for path in paths {
                    assert!(path.is_file(), "skill references must be files");
                    let name = path.file_name().unwrap().to_str().unwrap();
                    emit(
                        &out,
                        &mut assets,
                        &format!("{skill_root}/{skill}/references/{name}"),
                        &format!("{}\n", read(&format!("references/{name}"))),
                    );
                }
            }
        }
        let common = read(&root.join("surface/agents/common.md"));
        for name in ["arp4-worker", "arp4-reviewer"] {
            let dir = root.join("surface/agents").join(name);
            let description = read(&dir.join("description.txt"));
            let body = format!("{}\n\n{common}\n", read(&dir.join("body.md")));
            let (path, content) = if agent == "codex" {
                assert!(
                    !body.contains("'''"),
                    "agent instructions contain TOML literal delimiter"
                );
                (
                    format!(".codex/agents/{name}.toml"),
                    format!(
                        "# Generated by sync_docs; edit surface/agents.\nname = {name:?}\ndescription = {description:?}\ndeveloper_instructions = '''\n{body}'''\n"
                    ),
                )
            } else {
                let suffix = if agent == "github" {
                    ".agent.md"
                } else {
                    ".md"
                };
                let platform = if agent == "github" {
                    "user-invocable: false\n"
                } else {
                    ""
                };
                (
                    format!(".{agent}/agents/{name}{suffix}"),
                    format!(
                        "---\nname: {name}\ndescription: {description:?}\n{platform}---\n\n<!-- Generated by sync_docs; edit surface/agents. -->\n\n{body}"
                    ),
                )
            };
            emit(&out, &mut assets, &path, &content);
        }
    }
    fs::write(out.join("bundled_assets.rs"), format!("vec![\n{assets}]\n")).unwrap();
}
