"""テナント側の保存先の約束。実装は ``store`` と ``demo.memory_store``。

**業務層は SQL を知らない。** ここに出てくるのは業務の語彙だけで、
表の名前も pgvector も出てこない。
"""

from __future__ import annotations

from typing import Protocol

from kotonoha.tenant.models import ApiKey, Collection, Tenant


class TenantRepository(Protocol):
    """``t_tenant``。"""

    def find(self, tenant_id: str) -> Tenant | None: ...
    def save(self, tenant: Tenant) -> None: ...
    def all(self) -> list[Tenant]: ...


class ApiKeyRepository(Protocol):
    """``t_api_key``。"""

    def find(self, key_id: str) -> ApiKey | None: ...
    def save(self, key: ApiKey) -> None: ...
    def all(self) -> list[ApiKey]: ...
    def list_by_tenant(self, tenant_id: str) -> list[ApiKey]: ...


class CollectionRepository(Protocol):
    """``t_collection``。"""

    def find(self, collection_id: str) -> Collection | None: ...
    def find_by_name(self, tenant_id: str, name: str) -> Collection | None: ...
    def save(self, collection: Collection) -> None: ...
    def list_by_tenant(self, tenant_id: str) -> list[Collection]: ...
    def all(self) -> list[Collection]: ...
