"""取り込み側の保存先の約束。実装は ``store`` と ``demo.memory_store``。"""

from __future__ import annotations

from typing import Protocol

from kotonoha.ingest.models import Document, IngestJob, JobItem, StoredChunk


class DocumentRepository(Protocol):
    """``t_document``。"""

    def find(self, document_id: str) -> Document | None: ...
    def find_by_external_id(self, collection_id: str,
                            external_id: str) -> Document | None: ...
    def save(self, document: Document) -> None: ...
    def list_by_collection(self, collection_id: str) -> list[Document]: ...
    def delete(self, document_id: str) -> None: ...


class ChunkRepository(Protocol):
    """``t_chunk``。"""

    def save_many(self, chunks: list[StoredChunk]) -> None: ...
    def find(self, chunk_id: str) -> StoredChunk | None: ...
    def list_by_document(self, document_id: str) -> list[StoredChunk]: ...
    def list_by_collection(self, collection_id: str) -> list[StoredChunk]: ...
    def delete_by_document(self, document_id: str) -> int: ...
    def count_in_collection(self, collection_id: str) -> int: ...


class JobRepository(Protocol):
    """``t_ingest_job`` ``t_ingest_job_item``。"""

    def find(self, job_id: str) -> IngestJob | None: ...
    def save(self, job: IngestJob) -> None: ...
    def save_items(self, items: list[JobItem]) -> None: ...
    def save_item(self, item: JobItem) -> None: ...
    def find_item(self, job_id: str, seq_no: int) -> JobItem | None: ...
    def list_items(self, job_id: str) -> list[JobItem]: ...
    def list_by_tenant(self, tenant_id: str, limit: int = 50) -> list[IngestJob]: ...


class SourceStore(Protocol):
    """受け付けた原文の一時置き場。ジョブが終わるまで保つ。

    本番はオブジェクトストア。**API のプロセスに抱えない** ——
    5,000 件の本文をメモリに載せるとポッドが落ちる。
    """

    def put(self, job_id: str, sources: list) -> None: ...
    def take(self, job_id: str) -> list: ...
